import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import PrimeVue from 'primevue/config'
import VueApexCharts from 'vue3-apexcharts'
import ToastService from 'primevue/toastservice'
import 'bootstrap'
import 'primevue/resources/primevue.min.css'
import 'primevue/resources/themes/saga-blue/theme.css'
import 'primeicons/primeicons.css'
import 'primeflex/primeflex.min.css'
import Reconness from './plugins/reconness'

createApp(App).use(store).use(router).use(PrimeVue).use(VueApexCharts).use(ToastService).use(Reconness).mount('#app')
